buildscript {
    ext.kotlin_version = "1.4.31"
    repositories {
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
        jcenter()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
        jcenter()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
}

ext {
    compileSdkVersion = 30
    buildToolsVersion = "28.0.2"
    targetSdkVersion = 30
    versionName = '1.0'
    versionCode = 1
    xVersion = '1.1.0'
    blackReflection = '1.1.2'
}
